version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - /your_home/myapp/tmp/db:/var/lib/postgresql/data:z
    user: postgres:postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
  web:
    build: .
    image: myapp_web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - /your_home/myapp:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
